import "../../blocks/Input/input"
import "./footer.scss"
import "./_type/_large/footer_type_large.scss"
import "./_type/_simple/footer_type_simple.scss"
import "@fortawesome/fontawesome-free/css/all.css"
